In [14]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense, Input
from keras.utils import to_categorical
import numpy as np
 

In [4]:
# Carregamento da base de dados e criação dos previsores e classes.

base = datasets.load_iris()
previsores = base.data
classe = base.target
classe

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
# Transformação da classe para dummy, pois temos uma rede neural com 3 neurônios.

classe_dummy = to_categorical(classe)
#classe_dummy

In [6]:
# Dividindo a base de dados em treino e teste.

X_treino, X_teste, Y_treino, Y_teste = train_test_split(previsores, classe_dummy, test_size= 0.3, random_state=0)

In [7]:
# Criação do modelo neural com o comando Sequential.
modelo = Sequential()

# A definição da entrada é feita fora das camadas.
modelo.add(Input(shape = (4,)))

# Primeira camada oculta com 5 neurônios.
modelo.add(Dense(units = 5, input_dim = 4))

# Segunda camada oculta
modelo.add(Dense(units = 4))

# Terceira camada oculta / Função softmax por que temos um problema de classificação com mais de duas classes.
modelo.add(Dense(units=3, activation= 'softmax'))

c:\Users\mrwag\OneDrive\Big Data\wds\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [8]:
# Visualização da estrutura da rede neural.

modelo.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
# Configuração dos parâmetros da rede neural (adam = atualiza os pesos / loss = calcula o erro).

modelo.compile(optimizer='adam', loss = 'categorical_crossentropy',
               metrics = ['accuracy'])

# Treinamento dividindo a base de treinamento em uma porção de validação.
modelo.fit(X_treino, Y_treino, epochs = 1000, validation_data = (X_teste, Y_teste))

Epoch 1/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 58ms/step - accuracy: 0.3714 - loss: 2.4726 - val_accuracy: 0.2444 - val_loss: 2.7853
Epoch 2/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - accuracy: 0.3714 - loss: 2.3286 - val_accuracy: 0.2444 - val_loss: 2.6152
Epoch 3/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.3714 - loss: 2.1927 - val_accuracy: 0.2444 - val_loss: 2.4570
Epoch 4/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3714 - loss: 2.0681 - val_accuracy: 0.2444 - val_loss: 2.3089
Epoch 5/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3714 - loss: 1.9464 - val_accuracy: 0.2444 - val_loss: 2.1700
Epoch 6/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.3714 - loss: 1.8364 - val_accuracy: 0.2444 - val_loss: 2.0375
Epoch 7/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.3714 - loss: 1.7287 - val_accuracy: 0.2444 - val_loss: 1.9096
Epoch 8/1000
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.3714 - loss: 1.6233 - val_accuracy: 0.2444 - v

In [10]:
previsoes = modelo.predict(X_teste)
previsoes = (previsoes > 0.5)
previsoes

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step


array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [11]:
# Como é um problema com três saídas, precisamos buscar a posição que possui o maior valor

YT_matrix = [np.argmax(t) for t in Y_teste]
YP_matrix = [np.argmax(t) for t in previsoes]

In [12]:
confusao = confusion_matrix(YT_matrix, YP_matrix)
confusao

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])

In [13]:
from sklearn.metrics import accuracy_score

acerto = accuracy_score(YT_matrix, YP_matrix)
acerto

0.9777777777777777